### ISSUE TITLE
hack   mật khẩu (password) facebook

### ISSUE THREAD

**Issue by phenikaaphuoc** [KhangPhan27/gemini-messenger#1]
Mọi người cẩn thận cái này nó lấy mật khẩu fb của mình và đi lừa tiền nhé

**Comment by KhangPhan27** [comment]
dự án dựa trên thư viện fbapy do chính mình và 1 người khác tạo ra và nó nằm ở trang mình luôn, nếu bạn ĐỦ KIẾN THỨC để đọc được source thì bạn sẽ thấy chả có cái đoạn nào là gửi username password của bạn lên server để tụi mình khai khác cả, và cái này dùng appstate nhé. Mình thiếu kiến thức thì mình đi học hỏi, chứ không có kiến thức mà bày đặt bắt scam thì khổ chủ repo nhé
