### ISSUE TITLE
Mã độc trong repo 

### ISSUE THREAD

**Issue by phenikaaphuoc** [KhangPhan27/gemini-messenger#2]
Mọi người cẩn thận repo này chứa mã đọc

**Comment by KhangPhan27** [comment]
Chập những lên đại học mà bày đặt mã độc, đọc đoạn nào mã độc chỉ ra lụm tiền

**Comment by phenikaaphuoc** [comment]
chả thằng nào cắm mã độc mà để cho bàn dân thiên hạ xem cả

**Comment by KhangPhan27** [comment]
Không obfuscate, giỏi thì chỉ ra đi, opensource mà? Thể hiện mà không thèm đọc source

**Comment by KhangPhan27** [comment]
Được cái mồm, cứ  lib nào của fb là mã độc, lừa đảo. Bấm link 18 vào đổ thừa à?

**Comment by phenikaaphuoc** [comment]
lấy private key facebook từ extention rồi dùng fbapy gửi private key đến  api máy chủ định sẵn

**Comment by phenikaaphuoc** [comment]
fb mất thì cũng mất rồi để đây cảnh báo mọi người thôi ai không tin mất thì chịu

**Comment by KhangPhan27** [comment]
Thì cứ chỉ ra đi, tự dưng chả có cái bằng chứng vẹo gì vào đây cảnh báo

**Comment by phenikaaphuoc** [comment]
người ngay thì việc gì phải dựng lên như chó dựng lông như vậy

**Comment by RFS-ADRENO** [comment]
> người ngay thì việc gì phải dựng lên như chó dựng lông như vậy

chó ỉa trước nhà không đuổi chứ chẳng lẽ vỗ tay à

**Comment by truong9c2208** [comment]
tưởng phenikaa giỏi lắm chứ ai giờ cũng đần ác =)))

**Comment by phenikaaphuoc** [comment]
kinh có nhiều nick thật đấy

**Comment by kurosp** [comment]
học phenika mà đần

**Comment by KhangPhan27** [comment]
Giờ cứ có mã độc nhả ra, nói một lần khôn tự hiểu, đừng có 2 3 cái issue quậy đục ao ở cái repo này. Nhấn link sex thì đừng vào đây đổ tội, cho là lấy thì cookie chỉ login thôi chứ đ có việc đổi pass. T tự tin m ngu thôi chứ cái phenika dạy không ngu đâu. Chưa từng thấy ai hơn t 4 5 tuổi mà ngu như m, nói mãi không hiểu mà cứ đăng issue rồi bảo dựng lông. Còn mấy acc trên là các thành viên trong lib fbapy. Toàn giao thức đơn giản, trẻ con lớp 10 nó đọc còn hiểu mà m học đại học mà dòm k hiểu kêu mã độc, trên núi xuống dòm mqtt, http method lạ lắm à?

**Comment by KhangPhan27** [comment]
> kinh có nhiều nick thật đấy

Giờ cứ có mã độc nhả ra, nói một lần khôn tự hiểu, đừng có 2 3 cái issue quậy đục ao ở cái repo này. Nhấn link sex thì đừng vào đây đổ tội, cho là lấy thì cookie chỉ login thôi chứ đ có việc đổi pass. T tự tin m ngu thôi chứ cái phenika dạy không ngu đâu. Chưa từng thấy ai hơn t 4 5 tuổi mà ngu như m, nói mãi không hiểu mà cứ đăng issue rồi bảo dựng lông. Còn mấy acc trên là các thành viên trong lib fbapy. Toàn giao thức đơn giản, trẻ con lớp 10 nó đọc còn hiểu mà m học đại học mà dòm k hiểu kêu mã độc, trên núi xuống dòm mqtt, http method lạ lắm à?

**Comment by KhangPhan27** [comment]
> người ngay thì việc gì phải dựng lên như chó dựng lông như vậy

Ba cái http, mqtt lạ lắm hay sao, phenika nó không dạy hay gì, nhỏ lớn chưa thấy mấy api của fb hay sao. Nào bỏ được tật ghen ăn tức ở đi rồi làm IT tiếp, chứ ngu như m không cạnh tranh nổi trong ngành này đâu.

**Comment by michioxd** [comment]
làm đồ án của mình cho xong đi rồi đi ghen ăn tức ở sau =)))
+1 close issue.

**Comment by phenikaaphuoc** [comment]
hải thì kinh rồi

**Comment by phenikaaphuoc** [comment]
nick của thằng wibu nhìn phát biết là 1 thằng rồi

**Comment by KhangPhan27** [comment]
Chứ nick thằng mặt như cl học phenikaa là được vào ngu ngu làm bộ hay ho bày đặt mã độc mã độc à
