### ISSUE TITLE
Mã độc trong code

### ISSUE THREAD

**Issue by phenikaaphuoc** [KhangPhan27/gemini-messenger#4]
trong code chứa mã độc hack mk fb

**Comment by NhatAnhDN** [comment]
> trong code chứa mã độc hack mk fb

Chứa cái djtmemay , fork file bot ở đâu trên replit r bị check chứ gì . Khóc cl 😒

**Comment by phenikaaphuoc** [comment]
nhắc cho ae biết thôi k tin tùy mặc dù t biết m cùng 1 acc

**Comment by KhangPhan27** [comment]
M yên tâm, t không trẩu như m đâu nhé. Toàn bộ chính chủ. M muốn làm việc gì, muốn cảnh báo gì m nôn acc fb m ra. Chứa mã độc ngta nói chứ đ tới lượt thằng bệnh hoạn coi phim sex dính phishing vào đây xàm c đâu phenikuu ạ

**Comment by KhangPhan27** [comment]
Học phenikaa mà giao thức đơn giản dòm ra mã độc, m giỏi thì vào profile m mò đến fb t, t review code đoạn nào độc t bank học phí cho m hết đại học nhé. Trường này dạy cho m ngu vậy học phí chắc cũng k đắt đâu. Thứ ngu mà lì

**Comment by phenikaaphuoc** [comment]
m có dám đến gặp t không
